on:
  push:
    # There is no way to restrict this trigger to protected branches here.
    # Instead, we check for protected branches in the reusable workflow at the
    # job level in the ci-scripts repo.
    branches:
jobs:
  jira-integration-push:
    uses: baltech-ag/ci-scripts/.github/workflows/jira_integration_push.yml@master
    secrets: inherit
